import turtle
# set turtle colour to black
turtle.color("black")
# draw upper part of base
turtle.begin_fill()
turtle.forward(200)
turtle.right(130)
# save location halfway to colour bottom red later
turtle.forward(40)
red_pos = turtle.pos()
red_heading = turtle.heading()
# finish base
turtle.right(50)
turtle.forward(150)
turtle.right(50)
turtle.forward(40)
turtle.end_fill()
turtle.up()
# finish red base
turtle.setpos(red_pos)
turtle.seth(red_heading)
turtle.color("red")
turtle.down()
turtle.begin_fill()
turtle.forward(40)
turtle.right(50)
turtle.forward(100)
turtle.right(50)
turtle.forward(40)
turtle.end_fill()
# chimneys
def chimney():
    turtle.down()
    turtle.color("orange")
    turtle.begin_fill()
    turtle.left(110)
    turtle.forward(35)
    turtle.right(90)
    turtle.forward(20)
    turtle.right(90)
    turtle.forward(50)
    turtle.end_fill()
    turtle.up()
turtle.home()
turtle.forward(60)
chimney()
turtle.home()
turtle.forward(140)
chimney()